# Generated by Django 4.1.6 on 2023-02-14 01:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CoachStats',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('stats', models.JSONField(default=dict)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_team', to='baseball.coach')),
            ],
            options={
                'verbose_name': 'Coach Stats',
                'verbose_name_plural': 'Coach Stats',
                'ordering': ['created'],
            },
        ),
    ]
