# Generated by Django 4.1.6 on 2023-02-14 00:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stats', models.JSONField(default={})),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_team', to='baseball.coach')),
            ],
            options={
                'verbose_name': 'Coach Stats',
                'verbose_name_plural': 'Coach Stats',
                'ordering': ['created_at'],
            },
        ),
    ]
