# Generated by Django 4.1.7 on 2023-03-03 01:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_teams', to='baseball.competition')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_teams', to='baseball.team')),
            ],
            options={
                'verbose_name': 'Competition Team',
                'verbose_name_plural': 'Competition Teams',
                'ordering': ['created'],
            },
        ),
    ]
