# Generated by Django 4.1.6 on 2023-02-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='coachstats',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deleted_by_cascade',
        ),
    ]
