# Generated by Django 4.1.6 on 2023-02-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_coachstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachstats',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
