# Generated by Django 4.1.6 on 2023-02-17 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_remove_coach_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('games_played_by_position', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_team', to='baseball.player')),
            ],
            options={
                'verbose_name': 'Player Stats',
                'verbose_name_plural': 'Player Stats',
                'ordering': ['created'],
            },
        ),
    ]
