# Generated by Django 4.1.6 on 2023-02-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_rename_number_coachstats_jersey_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachstats',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
