# Generated by Django 4.1.6 on 2023-02-17 23:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_playerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCompetitionStats',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_team', to='baseball.coach')),
            ],
            options={
                'verbose_name': 'Coach Stats',
                'verbose_name_plural': 'Coach Stats',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCompetitionStats',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_team', to='baseball.player')),
            ],
            options={
                'verbose_name': 'Player Stats',
                'verbose_name_plural': 'Player Stats',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='player',
        ),
        migrations.DeleteModel(
            name='CoachStats',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
