# Generated by Django 4.1.6 on 2023-02-18 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_coachcompetitionstats_playercompetitionstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcompetitionstats',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_competition', to='baseball.coach'),
        ),
        migrations.AlterField(
            model_name='playercompetitionstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_competition', to='baseball.player'),
        ),
    ]
