# Generated by Django 4.1.6 on 2023-02-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0007_competition_alter_coachcompetitionstats_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcompetitionstats',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_stats', to='baseball.competition'),
        ),
        migrations.AlterField(
            model_name='playercompetitionstats',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_stats', to='baseball.competition'),
        ),
    ]
