# Generated by Django 4.2 on 2023-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_remove_teamplayer_batting_totals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcoach',
            name='joined_team',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamcoach',
            name='left_team',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='joined_team',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='left_team',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
