# Generated by Django 4.2 on 2023-05-12 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_alter_teamcoach_joined_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFieldingStats',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Fielding Stats',
                'verbose_name_plural': 'Player Fielding Stats',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='playerpitchingstatsbyrole',
            name='outs_pitched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='baserunning_stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_player', to='baseball.playerbaserunningstats'),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='pitching_stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_player', to='baseball.playerpitchingstats'),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='fielding_stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_player', to='baseball.playerfieldingstats'),
        ),
    ]
