# Generated by Django 4.1.7 on 2023-03-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_competitionteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='record',
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='record',
            field=models.JSONField(default=dict),
        ),
    ]
