# Generated by Django 4.2 on 2023-05-20 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_alter_game_rules_alter_game_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='regulation_innings',
            field=models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='playerbattingstatsbylineupspot',
            name='lineup_spot',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
