# Generated by Django 4.2 on 2023-05-12 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_playerfieldingstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFieldingStatsByPosition',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'P'), (2, 'C'), (3, '1B'), (4, '2B'), (5, '3B'), (6, 'SS'), (7, 'LF'), (8, 'CF'), (9, 'RF')])),
                ('games_started', models.PositiveIntegerField(default=0)),
                ('games_subbed_in', models.PositiveIntegerField(default=0)),
                ('games_finished', models.PositiveIntegerField(default=0)),
                ('complete_games', models.PositiveIntegerField(default=0)),
                ('putouts', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('fielding_errors', models.PositiveIntegerField(default=0)),
                ('throwing_errors', models.PositiveIntegerField(default=0)),
                ('outs_played', models.PositiveIntegerField(default=0)),
                ('double_plays', models.PositiveIntegerField(default=0)),
                ('steals_against', models.PositiveIntegerField(default=0)),
                ('caught_stealing', models.PositiveIntegerField(default=0)),
                ('pickoffs', models.PositiveIntegerField(default=0)),
                ('pickoff_attempts', models.PositiveIntegerField(default=0)),
                ('passed_balls', models.PositiveIntegerField(default=0)),
                ('fielding_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_position', to='baseball.playerfieldingstats')),
            ],
            options={
                'verbose_name': 'Player Fielding Stats by Position',
                'verbose_name_plural': 'Player Fielding Stats by Position',
                'ordering': ['created'],
            },
        ),
    ]
