# Generated by Django 4.2 on 2023-05-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_game_regulation_innings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='baseball.competition'),
        ),
    ]
