# Generated by Django 4.2 on 2023-05-12 21:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_playerfieldingstatsbyposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBattingStats',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Batting Stats',
                'verbose_name_plural': 'Player Batting Stats',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBattingStatsByLineupSpot',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lineup_spot', models.PositiveSmallIntegerField()),
                ('fielding_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_position', to='baseball.playerbattingstats')),
            ],
            options={
                'verbose_name': 'Player Batting Stats by Lineup Spot',
                'verbose_name_plural': 'Player Batting Stats by Lineup Spot',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='batting_stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_player', to='baseball.playerbattingstats'),
        ),
    ]
