# Generated by Django 4.2 on 2023-05-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_alter_user_managers'),
        ('baseball', '0005_alter_game_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='core.organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
