# Generated by Django 4.1.7 on 2023-03-03 23:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_alter_coachcompetitionstats_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachTeamStats',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('record', models.JSONField(blank=True, default=dict, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Coach'), (1, 'Manager'), (2, 'Assistant Coach')], default=2)),
                ('joined_team', models.DateField(blank=True, null=True)),
                ('left_team', models.DateField(blank=True, null=True)),
                ('competition_coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseball.coachcompetitionstats')),
                ('competition_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseball.competitionteam')),
            ],
            options={
                'verbose_name': 'Coach Stats (Team)',
                'verbose_name_plural': 'Coach Stats (Team)',
                'ordering': ['created'],
            },
        ),
    ]
