# Generated by Django 4.1.7 on 2023-03-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0006_coachteamstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachteamstats',
            name='competition_coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_by_team', to='baseball.coachcompetitionstats'),
        ),
        migrations.AlterField(
            model_name='coachteamstats',
            name='competition_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_stats', to='baseball.competitionteam'),
        ),
    ]
