# Generated by Django 4.1.7 on 2023-03-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0007_alter_coachteamstats_competition_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachteamstats',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Coach'), (1, 'Manager'), (2, 'Assistant Coach')], default=0),
        ),
    ]
