# Generated by Django 4.2 on 2023-05-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0007_playerbattingstatsbylineupspot_complete_games_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerpitchingstatsbyrole',
            old_name='lefty_batters_faced',
            new_name='batters_faced_vs_left',
        ),
        migrations.RenameField(
            model_name='playerpitchingstatsbyrole',
            old_name='righty_batters_faced',
            new_name='batters_faced_vs_right',
        ),
    ]
