# Generated by Django 4.1.7 on 2023-03-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0008_alter_coachteamstats_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachCompetitionStats',
            new_name='CompetitionCoach',
        ),
        migrations.RenameModel(
            old_name='PlayerCompetitionStats',
            new_name='PlayerCompetition',
        ),
        migrations.RenameModel(
            old_name='CoachTeamStats',
            new_name='TeamCoach',
        ),
    ]
