# Generated by Django 4.2 on 2023-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0008_rename_lefty_batters_faced_playerpitchingstatsbyrole_batters_faced_vs_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='innings_per_game',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
