# Generated by Django 4.1.7 on 2023-03-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0009_rename_coachcompetitionstats_competitioncoach_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerCompetition',
            new_name='CompetitionPlayer',
        ),
    ]
