# Generated by Django 4.2 on 2023-05-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0009_competition_innings_per_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerfieldingstatsbyposition',
            name='caught_stealing',
        ),
        migrations.RemoveField(
            model_name='playerfieldingstatsbyposition',
            name='pickoff_attempts',
        ),
        migrations.RemoveField(
            model_name='playerfieldingstatsbyposition',
            name='pickoffs',
        ),
        migrations.RemoveField(
            model_name='playerfieldingstatsbyposition',
            name='steals_against',
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='caught_stealing_home_plate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='caught_stealing_second_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='caught_stealing_third_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='pickoff_attempts_first_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='pickoff_attempts_second_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='pickoff_attempts_third_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='pickoffs_first_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='pickoffs_second_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='pickoffs_third_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='steals_against_home_plate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='steals_against_second_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerfieldingstatsbyposition',
            name='steals_against_third_base',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
