# Generated by Django 4.2 on 2023-05-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0010_remove_playerfieldingstatsbyposition_caught_stealing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='advanced_to_second',
            new_name='advanced_to_second_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='advanced_to_third',
            new_name='advanced_to_third_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='caught_stealing_home',
            new_name='caught_stealing_home_plate',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='caught_stealing_second',
            new_name='caught_stealing_second_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='caught_stealing_third',
            new_name='caught_stealing_third_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='picked_off_first',
            new_name='picked_off_first_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='picked_off_second',
            new_name='picked_off_second_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='picked_off_third',
            new_name='picked_off_third_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='pickoff_attempts_first',
            new_name='pickoff_attempts_first_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='pickoff_attempts_second',
            new_name='pickoff_attempts_second_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='pickoff_attempts_third',
            new_name='pickoff_attempts_third_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='steals_home',
            new_name='steals_home_plate',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='steals_second',
            new_name='steals_second_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='steals_third',
            new_name='steals_third_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='thrown_out_at_home',
            new_name='thrown_out_at_home_plate',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='thrown_out_at_second',
            new_name='thrown_out_at_second_base',
        ),
        migrations.RenameField(
            model_name='playerbaserunningstats',
            old_name='thrown_out_at_third',
            new_name='thrown_out_at_third_base',
        ),
        migrations.RenameField(
            model_name='playerbattingstatsbylineupspot',
            old_name='fielding_stats',
            new_name='batting_stats',
        ),
    ]
