# Generated by Django 4.1.7 on 2023-03-08 18:08

import baseball.models.competition_team
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0010_rename_playercompetition_competitionplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcoach',
            name='jersey_number',
            field=models.PositiveSmallIntegerField(default=99, validators=[baseball.models.competition_team.validate_team_jersey_number]),
        ),
    ]
