# Generated by Django 4.2 on 2023-05-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0011_rename_advanced_to_second_playerbaserunningstats_advanced_to_second_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbattingstatsbylineupspot',
            name='batting_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_by_lineup_spot', to='baseball.playerbattingstats'),
        ),
    ]
