# Generated by Django 4.1.7 on 2023-03-08 18:08

import baseball.models.competition_team
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0011_teamcoach_jersey_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jersey_number', models.PositiveSmallIntegerField(default=99, validators=[baseball.models.competition_team.validate_team_jersey_number])),
                ('batting_totals', models.JSONField(default=dict)),
                ('fielding_totals', models.JSONField(default=dict)),
                ('pitching_totals', models.JSONField(default=dict)),
                ('joined_team', models.DateField(blank=True, null=True)),
                ('left_team', models.DateField(blank=True, null=True)),
                ('competition_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_by_team', to='baseball.competitionplayer')),
                ('competition_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_stats', to='baseball.competitionteam')),
            ],
            options={
                'verbose_name': 'Player Stats (Team)',
                'verbose_name_plural': 'Player Stats (Team)',
                'ordering': ['created'],
            },
        ),
    ]
