# Generated by Django 4.1.7 on 2023-03-08 18:09

import baseball.models.competition_team
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0012_teamplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcoach',
            name='jersey_number',
            field=models.PositiveSmallIntegerField(null=True, validators=[baseball.models.competition_team.validate_team_jersey_number]),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='jersey_number',
            field=models.PositiveSmallIntegerField(null=True, validators=[baseball.models.competition_team.validate_team_jersey_number]),
        ),
    ]
