# Generated by Django 4.1.7 on 2023-03-10 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0013_alter_teamcoach_jersey_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionplayer',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamcoach',
            name='competition_coach',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='competition_player',
        ),
        migrations.AddField(
            model_name='teamcoach',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_by_team', to='baseball.coach'),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_by_team', to='baseball.player'),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='baseball.competition'),
        ),
        migrations.DeleteModel(
            name='CompetitionCoach',
        ),
        migrations.DeleteModel(
            name='CompetitionPlayer',
        ),
    ]
