# Generated by Django 4.1.7 on 2023-03-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0014_remove_competitionplayer_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcoach',
            name='competition_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='baseball.competitionteam'),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='competition_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='baseball.competitionteam'),
        ),
    ]
