# Generated by Django 4.1.7 on 2023-03-10 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0015_alter_teamcoach_competition_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcoach',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teamcoach',
            name='competition_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_staff', to='baseball.competitionteam'),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='competition_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster', to='baseball.competitionteam'),
        ),
    ]
