# Generated by Django 4.1.7 on 2023-03-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0016_teamcoach_active_teamplayer_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='game_rules',
            field=models.JSONField(default=dict),
        ),
    ]
