# Generated by Django 4.1.7 on 2023-03-22 16:25

import baseball.models.game
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0018_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='baserunning_totals',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='TeamBoxScore',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('score_by_inning', models.JSONField(default=dict)),
                ('batting_stats', models.JSONField(default=dict)),
                ('fielding_stats', models.JSONField(default=dict)),
                ('pitching_stats', models.JSONField(default=dict)),
                ('baserunning_stats', models.JSONField(default=dict)),
                ('is_home_team', models.BooleanField(default=False)),
                ('competition_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='baseball.competitionteam')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='baseball.game', validators=[baseball.models.game.limit_teams])),
            ],
            options={
                'verbose_name': 'Box Score',
                'verbose_name_plural': 'Box Scores',
                'ordering': ['created'],
            },
        ),
    ]
