# Generated by Django 4.2 on 2023-05-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_middle_name_user_suffix_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
